### ISSUE TITLE
which version to use on split keyboard with column stagger? 

### ISSUE THREAD

**Issue by kanishkaverma** [Apsu/Canary#12]
Hey, 
Thank you for your hard work. I was wondering which of the layouts would work better on a sweep keyboard? would it be the ortho one? also what if I were to put the row stagger angle mod version on a split keyboard (iris, lily58pro) would it not work? 
Thanks again for your time. 
warmest regards,
Kanishka

**Comment by Apsu** [comment]
Anything can work, but ortho would be the one intended to map onto anything that is matrix-like, whether actual ortho or column-staggered. Row-stagger angle or traditional all *work* fine, it's just a question of slight changes in finger distances and which fingers you use for the lower left keys -- the angle modded version is the "worst" for matrix layouts but it's not a huge deal really.
