### ISSUE TITLE
Add layout images to readme

### ISSUE THREAD

**Issue by rszyma** [Apsu/Canary#15]
Maybe we could add some images of layouts to README besides ascii layouts. Some people might want to save an img of their new layout and have a quick look at it when they are still learning it.

[Canary staggered keyboard layout](http://www.keyboard-layout-editor.com/##@@_y:1&x:1.5&c=%23DB72A5&a:7&f:6%3B&=W&_c=%2367CCDB%3B&=L&_c=%2393DB94%3B&=Y&_c=%23DBAD88%3B&=P&=K&_x:1.75&c=%23DB8B7C%3B&=Z&=X&_c=%2393DB94%3B&=O&_c=%2367CCDB%3B&=U&_c=%23DB72A5%3B&=%2F%3B%3B&@_x:1.75%3B&=C&_c=%2367CCDB%3B&=R&_c=%2393DB94%3B&=S&_c=%23DBAD88&n:true%3B&=T&=B&_x:1.75&c=%23DB8B7C%3B&=F&_n:true%3B&=N&_c=%2393DB94%3B&=E&_c=%2367CCDB%3B&=I&_c=%23DB72A5%3B&=A&='%3B&@_x:2.25&c=%2367CCDB%3B&=J&_c=%2393DB94%3B&=V&_c=%23DBAD88%3B&=D&=G&=Q&_x:1.75&c=%23DB8B7C%3B&=M&=H&_c=%2393DB94%3B&=%2F%2F&_c=%2367CCDB%3B&=,&_c=%23DB72A5%3B&=.)
![Canary staggered keyboard layout](https://github.com/Apsu/Canary/assets/44318430/c3ae80df-468d-4d79-be63-737f1779e373)

[Canary orthogonal keyboard layout](http://www.keyboard-layout-editor.com/##@@_y:1&x:1&c=%23DB72A5&a:7&f:6%3B&=W&_c=%2367CCDB%3B&=L&_c=%2393DB94%3B&=Y&_c=%23DBAD88%3B&=P&=B&_x:1.25&c=%23DB8B7C%3B&=Z&=F&_c=%2393DB94%3B&=O&_c=%2367CCDB%3B&=U&_c=%23DB72A5%3B&='%3B&@_x:1%3B&=C&_c=%2367CCDB%3B&=R&_c=%2393DB94%3B&=S&_c=%23DBAD88&n:true%3B&=T&=G&_x:1.25&c=%23DB8B7C%3B&=M&_n:true%3B&=N&_c=%2393DB94%3B&=E&_c=%2367CCDB%3B&=I&_c=%23DB72A5%3B&=A%3B&@_x:1%3B&=Q&_c=%2367CCDB%3B&=J&_c=%2393DB94%3B&=V&_c=%23DBAD88%3B&=D&=K&_x:1.25&c=%23DB8B7C%3B&=X&=H&_c=%2393DB94%3B&=%2F%2F&_c=%2367CCDB%3B&=,&_c=%23DB72A5%3B&=.)
![Canary orthogonal keyboard layout](https://github.com/Apsu/Canary/assets/44318430/daae2537-41c7-4585-a7ea-8a092d0554b8)

**Comment by Apsu** [comment]
These are great, thanks for the suggestion! I'll probably add them soon.
