### ISSUE TITLE
[Mac Release] Caps Lock has letters from QWERTY bound

### ISSUE THREAD

**Issue by ianfromdover** [Apsu/Canary#7]
# Expected Behavior
On pressing `caps lock`, the letters should still be in the Canary layout.

# Actual Behavior
The keys are in this strange layout. Inspected with Ukulele.

<img width="1303" alt="Screenshot 2022-10-30 at 4 28 13 PM" src="https://user-images.githubusercontent.com/62384984/198869500-52fa9f53-f772-4304-b985-191993931598.png">

# Suggested Fix
Rebind the keys in `Canary.bundle` using Ukulele and re-release for Mac.

How do I contribute to a release file?

**Comment by ianfromdover** [comment]
I gave up and used Karabiner Elements, it allows me to rebind the caps lock and shortcuts too.

**Comment by Apsu** [comment]
If you want to contribute a fix, simply make a Pull Request with the corrected file and I'll review it. Thanks!
